version: "3.9"

services:
  app:
    container_name: app
    build:
      context: ./app/bin/build
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      -
  db:
    container_name: app_db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgres/data
  volumes:
    db_data:
