version: "3.9"

services:
  frontend:

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      -
  db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      -
