// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	Brackets     string
	Teams        string
	Tournaments  string
	UserAccounts string
	UserTokens   string
	UsersEmail   string
}{
	Brackets:     "brackets",
	Teams:        "teams",
	Tournaments:  "tournaments",
	UserAccounts: "user_accounts",
	UserTokens:   "user_tokens",
	UsersEmail:   "users_email",
}
