// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Brackets", testBracketsUpsert)

	t.Run("Teams", testTeamsUpsert)

	t.Run("Tournaments", testTournamentsUpsert)

	t.Run("UserAccounts", testUserAccountsUpsert)

	t.Run("UserTokens", testUserTokensUpsert)

	t.Run("UsersEmails", testUsersEmailsUpsert)
}
