// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testTournaments(t *testing.T) {
	t.Parallel()

	query := Tournaments()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testTournamentsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTournamentsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Tournaments().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTournamentsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TournamentSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testTournamentsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := TournamentExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Tournament exists: %s", err)
	}
	if !e {
		t.Errorf("Expected TournamentExists to return true, but got false.")
	}
}

func testTournamentsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	tournamentFound, err := FindTournament(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if tournamentFound == nil {
		t.Error("want a record, got nil")
	}
}

func testTournamentsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Tournaments().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testTournamentsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Tournaments().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testTournamentsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	tournamentOne := &Tournament{}
	tournamentTwo := &Tournament{}
	if err = randomize.Struct(seed, tournamentOne, tournamentDBTypes, false, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}
	if err = randomize.Struct(seed, tournamentTwo, tournamentDBTypes, false, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tournamentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tournamentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Tournaments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testTournamentsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	tournamentOne := &Tournament{}
	tournamentTwo := &Tournament{}
	if err = randomize.Struct(seed, tournamentOne, tournamentDBTypes, false, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}
	if err = randomize.Struct(seed, tournamentTwo, tournamentDBTypes, false, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = tournamentOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = tournamentTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func tournamentBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func tournamentAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Tournament) error {
	*o = Tournament{}
	return nil
}

func testTournamentsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Tournament{}
	o := &Tournament{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, tournamentDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Tournament object: %s", err)
	}

	AddTournamentHook(boil.BeforeInsertHook, tournamentBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	tournamentBeforeInsertHooks = []TournamentHook{}

	AddTournamentHook(boil.AfterInsertHook, tournamentAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	tournamentAfterInsertHooks = []TournamentHook{}

	AddTournamentHook(boil.AfterSelectHook, tournamentAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	tournamentAfterSelectHooks = []TournamentHook{}

	AddTournamentHook(boil.BeforeUpdateHook, tournamentBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	tournamentBeforeUpdateHooks = []TournamentHook{}

	AddTournamentHook(boil.AfterUpdateHook, tournamentAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	tournamentAfterUpdateHooks = []TournamentHook{}

	AddTournamentHook(boil.BeforeDeleteHook, tournamentBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	tournamentBeforeDeleteHooks = []TournamentHook{}

	AddTournamentHook(boil.AfterDeleteHook, tournamentAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	tournamentAfterDeleteHooks = []TournamentHook{}

	AddTournamentHook(boil.BeforeUpsertHook, tournamentBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	tournamentBeforeUpsertHooks = []TournamentHook{}

	AddTournamentHook(boil.AfterUpsertHook, tournamentAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	tournamentAfterUpsertHooks = []TournamentHook{}
}

func testTournamentsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTournamentsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(tournamentColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testTournamentToManyBrackets(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b, c Bracket

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, bracketDBTypes, false, bracketColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, bracketDBTypes, false, bracketColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.TournamentID, a.ID)
	queries.Assign(&c.TournamentID, a.ID)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.Brackets().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.TournamentID, b.TournamentID) {
			bFound = true
		}
		if queries.Equal(v.TournamentID, c.TournamentID) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := TournamentSlice{&a}
	if err = a.L.LoadBrackets(ctx, tx, false, (*[]*Tournament)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Brackets); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.Brackets = nil
	if err = a.L.LoadBrackets(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.Brackets); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testTournamentToManyAddOpBrackets(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b, c, d, e Bracket

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, false, strmangle.SetComplement(tournamentPrimaryKeyColumns, tournamentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Bracket{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bracketDBTypes, false, strmangle.SetComplement(bracketPrimaryKeyColumns, bracketColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*Bracket{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddBrackets(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.ID, first.TournamentID) {
			t.Error("foreign key was wrong value", a.ID, first.TournamentID)
		}
		if !queries.Equal(a.ID, second.TournamentID) {
			t.Error("foreign key was wrong value", a.ID, second.TournamentID)
		}

		if first.R.Tournament != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.Tournament != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.Brackets[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.Brackets[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.Brackets().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testTournamentToManySetOpBrackets(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b, c, d, e Bracket

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, false, strmangle.SetComplement(tournamentPrimaryKeyColumns, tournamentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Bracket{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bracketDBTypes, false, strmangle.SetComplement(bracketPrimaryKeyColumns, bracketColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetBrackets(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Brackets().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetBrackets(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Brackets().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.TournamentID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.TournamentID) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.ID, d.TournamentID) {
		t.Error("foreign key was wrong value", a.ID, d.TournamentID)
	}
	if !queries.Equal(a.ID, e.TournamentID) {
		t.Error("foreign key was wrong value", a.ID, e.TournamentID)
	}

	if b.R.Tournament != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Tournament != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Tournament != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.Tournament != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.Brackets[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.Brackets[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testTournamentToManyRemoveOpBrackets(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b, c, d, e Bracket

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, false, strmangle.SetComplement(tournamentPrimaryKeyColumns, tournamentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*Bracket{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, bracketDBTypes, false, strmangle.SetComplement(bracketPrimaryKeyColumns, bracketColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddBrackets(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.Brackets().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveBrackets(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.Brackets().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.TournamentID) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.TournamentID) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.Tournament != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.Tournament != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.Tournament != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.Tournament != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.Brackets) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.Brackets[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.Brackets[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testTournamentToOneUserAccountUsingCreatedByUserUserAccount(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Tournament
	var foreign UserAccount

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userAccountDBTypes, false, userAccountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize UserAccount struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&local.CreatedByUser, foreign.ID)
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.CreatedByUserUserAccount().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if !queries.Equal(check.ID, foreign.ID) {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	ranAfterSelectHook := false
	AddUserAccountHook(boil.AfterSelectHook, func(ctx context.Context, e boil.ContextExecutor, o *UserAccount) error {
		ranAfterSelectHook = true
		return nil
	})

	slice := TournamentSlice{&local}
	if err = local.L.LoadCreatedByUserUserAccount(ctx, tx, false, (*[]*Tournament)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.CreatedByUserUserAccount == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.CreatedByUserUserAccount = nil
	if err = local.L.LoadCreatedByUserUserAccount(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.CreatedByUserUserAccount == nil {
		t.Error("struct should have been eager loaded")
	}

	if !ranAfterSelectHook {
		t.Error("failed to run AfterSelect hook for relationship")
	}
}

func testTournamentToOneSetOpUserAccountUsingCreatedByUserUserAccount(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b, c UserAccount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, false, strmangle.SetComplement(tournamentPrimaryKeyColumns, tournamentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userAccountDBTypes, false, strmangle.SetComplement(userAccountPrimaryKeyColumns, userAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userAccountDBTypes, false, strmangle.SetComplement(userAccountPrimaryKeyColumns, userAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*UserAccount{&b, &c} {
		err = a.SetCreatedByUserUserAccount(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.CreatedByUserUserAccount != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.CreatedByUserTournaments[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if !queries.Equal(a.CreatedByUser, x.ID) {
			t.Error("foreign key was wrong value", a.CreatedByUser)
		}

		zero := reflect.Zero(reflect.TypeOf(a.CreatedByUser))
		reflect.Indirect(reflect.ValueOf(&a.CreatedByUser)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if !queries.Equal(a.CreatedByUser, x.ID) {
			t.Error("foreign key was wrong value", a.CreatedByUser, x.ID)
		}
	}
}

func testTournamentToOneRemoveOpUserAccountUsingCreatedByUserUserAccount(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Tournament
	var b UserAccount

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, tournamentDBTypes, false, strmangle.SetComplement(tournamentPrimaryKeyColumns, tournamentColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userAccountDBTypes, false, strmangle.SetComplement(userAccountPrimaryKeyColumns, userAccountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = a.SetCreatedByUserUserAccount(ctx, tx, true, &b); err != nil {
		t.Fatal(err)
	}

	if err = a.RemoveCreatedByUserUserAccount(ctx, tx, &b); err != nil {
		t.Error("failed to remove relationship")
	}

	count, err := a.CreatedByUserUserAccount().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 0 {
		t.Error("want no relationships remaining")
	}

	if a.R.CreatedByUserUserAccount != nil {
		t.Error("R struct entry should be nil")
	}

	if !queries.IsValuerNil(a.CreatedByUser) {
		t.Error("foreign key value should be nil")
	}

	if len(b.R.CreatedByUserTournaments) != 0 {
		t.Error("failed to remove a from b's relationships")
	}
}

func testTournamentsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTournamentsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := TournamentSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testTournamentsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Tournaments().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	tournamentDBTypes = map[string]string{`ID`: `uuid`, `SportName`: `character varying`, `Title`: `character varying`, `StartAt`: `timestamp without time zone`, `EndAt`: `timestamp without time zone`, `Description`: `json`, `CreatedByUser`: `bigint`, `BracketsLimit`: `integer`, `IsActive`: `boolean`}
	_                 = bytes.MinRead
)

func testTournamentsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(tournamentPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(tournamentAllColumns) == len(tournamentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testTournamentsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(tournamentAllColumns) == len(tournamentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Tournament{}
	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, tournamentDBTypes, true, tournamentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(tournamentAllColumns, tournamentPrimaryKeyColumns) {
		fields = tournamentAllColumns
	} else {
		fields = strmangle.SetComplement(
			tournamentAllColumns,
			tournamentPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := TournamentSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testTournamentsUpsert(t *testing.T) {
	t.Parallel()

	if len(tournamentAllColumns) == len(tournamentPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Tournament{}
	if err = randomize.Struct(seed, &o, tournamentDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Tournament: %s", err)
	}

	count, err := Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, tournamentDBTypes, false, tournamentPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Tournament struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Tournament: %s", err)
	}

	count, err = Tournaments().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
