output = "./boiler-models"
wipe = true
pkgname = "model"
add-enum-types = true
[psql]
  dbname = "main"
  host   = "host.docker.internal"
  port   = 5432
  user   = "blank"
  pass   = "qwerty"
  sslmode = "disable"
#  schema = "schema"
#  blacklist = ["migrations", "other"]
# [auto-columns]
#     created = "created_on"



#//go:generate sqlboiler --wipe psql
#GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO username;